<LoadingScreen>:
    MDFloatLayout:
        Image:
            source: "assets/logo.png"
            pos_hint: {"center_x": 0.5, "center_y": 0.7}
            size_hint: 1,0.6
        Image:
            source: "assets/loading.gif"
            pos_hint: {"center_x": 0.5, "center_y": 0.45}
            size_hint: 1,0.3
            allow_stretch: True
            anim_delay: 0.03
            anim_reset: True
